// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyAudioPreset(arg1) {
  return window['go']['main']['App']['ApplyAudioPreset'](arg1);
}

export function GetAudioPresets() {
  return window['go']['main']['App']['GetAudioPresets']();
}

export function GetDefaults() {
  return window['go']['main']['App']['GetDefaults']();
}

export function GetMode() {
  return window['go']['main']['App']['GetMode']();
}

export function GetMonitors() {
  return window['go']['main']['App']['GetMonitors']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ResetAll(arg1) {
  return window['go']['main']['App']['ResetAll'](arg1);
}

export function ResetAudio() {
  return window['go']['main']['App']['ResetAudio']();
}

export function ResetVideo() {
  return window['go']['main']['App']['ResetVideo']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}
