// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';
import {video} from '../models';

export function ApplyAudioPreset(arg1:string):Promise<settings.Settings>;

export function GetAudioPresets():Promise<Array<settings.AudioPreset>>;

export function GetDefaults():Promise<settings.Settings>;

export function GetMode():Promise<string>;

export function GetMonitors():Promise<Array<video.MonitorInfo>>;

export function GetSettings():Promise<settings.Settings>;

export function ResetAll(arg1:boolean):Promise<settings.Settings>;

export function ResetAudio():Promise<settings.Settings>;

export function ResetVideo():Promise<settings.Settings>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function SetMode(arg1:string):Promise<void>;

export function TestConnection():Promise<void>;
