import 'package:flutter/material.dart';

/// Curated preset cards. Each preset references a locally-rendered
/// animation by [animId] — we no longer push WLED's built-in fx IDs.
/// The app streams DRGB UDP frames generated by the matching PresetAnim.
class EffectPreset {
  final String name;
  final String tagline;
  final IconData icon;
  final List<Color> swatch;
  /// Identifier into [animFor] in render/anim_registry.dart.
  final String animId;
  /// When true, the tile powers the strip off instead of streaming frames.
  final bool off;

  const EffectPreset({
    required this.name,
    required this.tagline,
    required this.icon,
    required this.swatch,
    required this.animId,
    this.off = false,
  });
}

const curatedPresets = <EffectPreset>[
  // Sentinel: turn LEDs off entirely.
  EffectPreset(
    name: 'Off',
    tagline: 'lights out',
    icon: Icons.power_settings_new_rounded,
    swatch: [Color(0xFF11161D), Color(0xFF1D2530), Color(0xFF252E3B)],
    animId: '',
    off: true,
  ),
  // ---- Cinematic / atmospheric ----
  EffectPreset(
    name: 'Pacifica',
    tagline: 'deep ocean swell',
    icon: Icons.water,
    swatch: [Color(0xFF003E6F), Color(0xFF0097A7), Color(0xFF80DEEA)],
    animId: 'pacifica',
  ),
  EffectPreset(
    name: 'Aurora',
    tagline: 'northern lights',
    icon: Icons.waves,
    swatch: [Color(0xFF00E5FF), Color(0xFF7C4DFF), Color(0xFF00C853)],
    animId: 'aurora',
  ),
  EffectPreset(
    name: 'Nebula',
    tagline: 'cosmic dust',
    icon: Icons.blur_circular,
    swatch: [Color(0xFF311B92), Color(0xFFD500F9), Color(0xFF00B8D4)],
    animId: 'nebula',
  ),
  EffectPreset(
    name: 'Galaxy',
    tagline: 'starfield drift',
    icon: Icons.auto_awesome,
    swatch: [Color(0xFF1A237E), Color(0xFF7C4DFF), Color(0xFFFFFFFF)],
    animId: 'galaxy',
  ),
  // ---- Fire family ----
  EffectPreset(
    name: 'Embers',
    tagline: 'fading firelight',
    icon: Icons.local_fire_department,
    swatch: [Color(0xFF7F0000), Color(0xFFB71C1C), Color(0xFFFF6F00)],
    animId: 'embers',
  ),
  EffectPreset(
    name: 'Fire',
    tagline: 'crackling hearth',
    icon: Icons.local_fire_department,
    swatch: [Color(0xFFFF6F00), Color(0xFFE65100), Color(0xFFBF360C)],
    animId: 'fire',
  ),
  EffectPreset(
    name: 'Inferno',
    tagline: 'roaring flames',
    icon: Icons.whatshot,
    swatch: [Color(0xFFFFEB3B), Color(0xFFFF6F00), Color(0xFFB71C1C)],
    animId: 'inferno',
  ),
  EffectPreset(
    name: 'Candle',
    tagline: 'single flame flicker',
    icon: Icons.emoji_objects,
    swatch: [Color(0xFFFFB300), Color(0xFFFF6F00), Color(0xFFE65100)],
    animId: 'candle',
  ),
  EffectPreset(
    name: 'Candelabra',
    tagline: 'multi candle flicker',
    icon: Icons.local_fire_department,
    swatch: [Color(0xFFFFD180), Color(0xFFFF8A65), Color(0xFFD84315)],
    animId: 'candelabra',
  ),
  // ---- Day cycle ----
  EffectPreset(
    name: 'Sunrise',
    tagline: 'gradual dawn',
    icon: Icons.wb_sunny,
    swatch: [Color(0xFFFFE082), Color(0xFFFFAB91), Color(0xFFFF8A65)],
    animId: 'sunrise',
  ),
  EffectPreset(
    name: 'Sunset',
    tagline: 'warm horizon',
    icon: Icons.wb_twilight,
    swatch: [Color(0xFFFFC107), Color(0xFFFF6F00), Color(0xFFD81B60)],
    animId: 'sunset',
  ),
  EffectPreset(
    name: 'Moonlight',
    tagline: 'cool silver glow',
    icon: Icons.nightlight_round,
    swatch: [Color(0xFFE3F2FD), Color(0xFFB3E5FC), Color(0xFF90A4AE)],
    animId: 'moonlight',
  ),
  // ---- Cold / winter ----
  EffectPreset(
    name: 'Snowfall',
    tagline: 'gentle drift',
    icon: Icons.ac_unit,
    swatch: [Color(0xFFFFFFFF), Color(0xFFB3E5FC), Color(0xFF1E88E5)],
    animId: 'snowfall',
  ),
  EffectPreset(
    name: 'Frostbite',
    tagline: 'arctic shimmer',
    icon: Icons.severe_cold,
    swatch: [Color(0xFFE0F7FA), Color(0xFF00BCD4), Color(0xFF00838F)],
    animId: 'frostbite',
  ),
  // ---- Vibe / texture ----
  EffectPreset(
    name: 'Lava Lamp',
    tagline: 'slow bubbles',
    icon: Icons.bubble_chart,
    swatch: [Color(0xFFFF6F00), Color(0xFFD500F9), Color(0xFFFFD600)],
    animId: 'lava',
  ),
  EffectPreset(
    name: 'Tropics',
    tagline: 'lagoon palette',
    icon: Icons.beach_access,
    swatch: [Color(0xFF00E5FF), Color(0xFFFFD600), Color(0xFFFF6E40)],
    animId: 'tropics',
  ),
  EffectPreset(
    name: 'Rainforest',
    tagline: 'humid greens',
    icon: Icons.forest,
    swatch: [Color(0xFF1B5E20), Color(0xFF66BB6A), Color(0xFFCDDC39)],
    animId: 'rainforest',
  ),
  EffectPreset(
    name: 'Vapor',
    tagline: 'retro pastel wash',
    icon: Icons.blur_on,
    swatch: [Color(0xFFFF80AB), Color(0xFF80D8FF), Color(0xFFB388FF)],
    animId: 'vapor',
  ),
  EffectPreset(
    name: 'Plasma',
    tagline: 'liquid magenta',
    icon: Icons.bubble_chart,
    swatch: [Color(0xFFD500F9), Color(0xFF651FFF), Color(0xFF00E5FF)],
    animId: 'plasma',
  ),
  // ---- High-energy ----
  EffectPreset(
    name: 'Cyberpunk',
    tagline: 'neon chase',
    icon: Icons.electric_bolt,
    swatch: [Color(0xFFFF1744), Color(0xFF00E5FF), Color(0xFFD500F9)],
    animId: 'cyberpunk',
  ),
  EffectPreset(
    name: 'Lightning',
    tagline: 'storm bolts',
    icon: Icons.bolt,
    swatch: [Color(0xFFFFFFFF), Color(0xFF7C4DFF), Color(0xFF263238)],
    animId: 'lightning',
  ),
  EffectPreset(
    name: 'Police',
    tagline: 'red & blue flash',
    icon: Icons.local_police,
    swatch: [Color(0xFF1E88E5), Color(0xFFE53935), Color(0xFFFFFFFF)],
    animId: 'police',
  ),
  // ---- Living things ----
  EffectPreset(
    name: 'Heartbeat',
    tagline: 'lub-dub pulse',
    icon: Icons.favorite,
    swatch: [Color(0xFF7F0000), Color(0xFFE53935), Color(0xFFB71C1C)],
    animId: 'heartbeat',
  ),
  EffectPreset(
    name: 'Breathe',
    tagline: 'slow inhale',
    icon: Icons.air,
    swatch: [Color(0xFF7CCBE6), Color(0xFF3B6E84), Color(0xFF11161D)],
    animId: 'breathe',
  ),
  EffectPreset(
    name: 'Rainbow',
    tagline: 'classic cycle',
    icon: Icons.color_lens,
    swatch: [Color(0xFFE53935), Color(0xFFFFEB3B), Color(0xFF1E88E5)],
    animId: 'rainbow',
  ),
  EffectPreset(
    name: 'Candy',
    tagline: 'pastel sweep',
    icon: Icons.cake,
    swatch: [Color(0xFFF8BBD0), Color(0xFFB2EBF2), Color(0xFFFFF59D)],
    animId: 'candy',
  ),
];
